#!/usr/bin/env bash
# Installs and configure HAproxy on a server.

apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.6

# Update system
apt-get -y update

# Install HAproxy
apt-get -y install haproxy

# Configure HAproxy
sed -i -e '$aENABLED=1\n' /etc/default/haproxy
sed -i -e '$a\listen balancer\n\tbind :80\n\tbalance roundrobin\n\tserver 415156-web-01 18.214.87.211 check\n\tserver 415156-web-02 54.157.135.59 check\n' /etc/haproxy/haproxy.cfg

# Restart HAproxy
service haproxy restart
