#!/usr/bin/env bash
# This configures an Nginx server to listen on port 80.

rm /etc/nginx/sites-enabled/default
ln /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# Restart Nginx
service nginx restart
