#!/usr/bin/env bash

while IFS=: read -r user pass uid gid info home shell; do
    echo "The user $user is part of the $gid gang, lives in $home and rides $shell."
    echo "User ID's place is protected by the passcode $pass, more info about the user here: $info"
    echo
done < /etc/passwd
